# This is a basic workflow to help you get started with Actions

name: generate_plot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas matplotlib scikit-learn
      # Runs a single command using the runners shell
      - name: Generates a plot and saves it to the repository.
        run: python testscript.py
      # We want to save this file to the repository
      ## I got this code from here: https://github.com/orgs/community/discussions/26672
      #- name: Commit the file to the repository
      #  id: commit
      #  run: |
      #    git config --local user.email "action@github.com"
      #    git config --local user.name "github-actions"
      #    git add iris_plot.pdf
      #    if [-z "$(git status --porcelain)"]; then
      #       echo "::set-output name=push::false"
      #    else
      #       git commit -m "Add changes" -a
      #       echo "::set-output name=push::true"
      #    fi
      #  shell: bash
      #- name: Push changes
      #  if: steps.commit.outputs.push == 'true'
      #  uses: ad-m/github-push-action@master
      #  with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      # This code is from this directory:
      #  https://www.amitgrinson.com/blog/automated-plot-with-github-actions/
      - name: Commit the plot to the repository
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add iris_plot.pdf
          git commit -m 'Re-build package plot' || echo "No changes to commit"
          git push origin || echo "No changes to commit"